# Generated by Django 3.1.7 on 2021-05-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=200)),
                ('data_ur', models.DateField()),
                ('pesel', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Premia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiekosc', models.PositiveIntegerField(default=0)),
                ('uzasadnienie', models.TextField(max_length=7000)),
                ('awans', models.BooleanField(default=0)),
                ('data', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Projekty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('data_roz', models.DateTimeField(verbose_name='date published')),
                ('data_zak', models.DateField()),
                ('koszty', models.PositiveIntegerField()),
                ('profit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stanowiska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('dzial', models.CharField(max_length=100)),
                ('braki', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Zatrudnienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_data', models.DateTimeField(verbose_name='date published')),
                ('do_data', models.DateField()),
                ('pensja', models.PositiveIntegerField()),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pracownicy')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.projekty')),
                ('stanowisko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.stanowiska')),
            ],
        ),
        migrations.CreateModel(
            name='Urlopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_data', models.DateTimeField(verbose_name='date published')),
                ('do_data', models.DateField()),
                ('miejsce_pobytu', models.CharField(max_length=200)),
                ('rodzaj_zwolnienia', models.CharField(choices=[('Wy', 'Wypoczynkowy'), ('Ok', 'Okolicznosciowy'), ('Op', 'Opieka_nad_dzieckiem'), ('Sz', 'Szkolenia'), ('Za', 'Zadanie'), ('Be', 'Bezplatny')], max_length=2)),
                ('id_pracownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pracownicy')),
            ],
        ),
        migrations.CreateModel(
            name='Szkolenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('certyfikat', models.BooleanField()),
                ('data', models.DateField()),
                ('cena', models.PositiveIntegerField()),
                ('dofinansowanie', models.PositiveIntegerField()),
                ('id_pracownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pracownicy')),
            ],
        ),
        migrations.CreateModel(
            name='Rekrutacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=200)),
                ('upload_CV', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('pesel', models.DecimalField(decimal_places=0, max_digits=11)),
                ('akceptacja', models.BooleanField()),
                ('id_stanowiska', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.stanowiska')),
            ],
        ),
    ]
